[package]
name = "ui-gtk"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "*"
tracing-subscriber = "*"

serde_json = "*"

tokio = { version = "*", features = ["full"] }
gtk = { version = "*", package = "gtk4", features = ["v4_22"] }
adw = { version = "*", package = "libadwaita", features = ["v1_7"] }
async-channel = "*"
async-trait = "*"

anyhow = "*"
thiserror = "*"

sourceview5 = "*"

directories = "*"

# projects
silo-base = { path = "../silo-base" }
silo-plugin = { path = "../silo-plugin" }

postgres = { path = "../../plugins/postgres" }
mysql-plugin = { path = "../../plugins/mysql-plugin" }


[build-dependencies]
gio = "*"
glib-build-tools = "*"
