[package]
name = "silo"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "*"
tracing = "*"
tracing-subscriber = "*"

anyhow = "*"
thiserror = "*"

gtk = { version = "*", package = "gtk4", features = ["v4_22"] }
adw = { version = "*", package = "libadwaita", features = ["v1_7"] }

# projects
silo-api = { path = "../silo-api" }
silo-base = { path = "../libs/silo-base" }
#ui-relm = { path = "../libs/ui-relm" }
ui-gtk = { path = "../libs/ui-gtk" }


[build-dependencies]
gio = "*"
glib-build-tools = "*"
