[package]
name = "silo"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "*"
tracing = "*"
tracing-subscriber = "*"

gtk = { version = "*", package = "gtk4", features = ["v4_6"] }

# projects
silo-base = { path = "../libs/silo-base" }
#ui-relm = { path = "../libs/ui-relm" }
ui-gtk = { path = "../libs/ui-gtk" }
